baseURL = "https://kurgalinn.github.io/"
title = "Home"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
author = "Nikita Kurgalin"
description = "My personal website"
keywords = "blog,developer,php"
info = "PHP Backend Developer"
avatarURL = "images/avatar.jpg"
footerContent = "Enter a text here."

dateFormat = "January 2, 2006"

hideFooter = true
hideCredits = true
hideCopyright = true
since = 2020

rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5

# Enable Twemoji
enableTwemoji = true

# Custom CSS
customCSS = []

# Custom SCSS
customSCSS = []

# Custom JS
customJS = []

[taxonomies]
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/kurgalinn"
[[params.social]]
name = "Medium"
icon = "fa fa-medium"
weight = 5
url = "https://medium.com/@nikita.kurgalin"
[[params.social]]
name = "Habr.Career"
icon = "fa fa-file-text"
weight = 4
url = "https://career.habr.com/papillon-27746"


[languages]
[languages.en]
languageName = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[languages.ru]
languageName = "Русский"
title = "Главная"

[languages.ru.params]
author = "Никита Кургалин"
info = "PHP-разработчик"
description = "Персональный сайт"
keywords = "блог,разработка,php"
footerContent = "Enter a text here."

[languages.ru.menu]

[[languages.ru.menu.main]]
name = "Блог"
weight = 2
url = "posts/"